### ISSUE TITLE
[FEATURE] specify source code directory (subfolder)

### ISSUE THREAD

**Issue by brylie-wolt** [christopherpickering/pre-commit-hooks#1]
## Feature Request

Our project has a subdirectory for the app source code, such as the following structure.

- `/` (git project root)
    - `app/` - source code including `pyproject.toml` and `poetry.lock`
    - `docs/` - documentation like README

It would be helpful to specify the source code directory, so the hook would find the `pyproject.toml` and generate the `requirements.txt` at the same level. 

```yaml
repos:
  - repo: https://github.com/christopherpickering/pre-commit-hooks
    rev: <VERSION> # Get the latest from: https://github.com/christopherpickering/pre-commit-hooks/releases
    hooks:
      - id: poetry-to-requirements
        args: [--dev,--input=subfolder/pyproject.toml,--output=subfolder/requirements.txt]
```

We have, for example, configured our deployment service to find the project source code in the `app/` directory.
